### PR TITLE
Update minimum required version

### PR DESCRIPTION
**Pull request by LeeLenaleee**
Forgot to update the required version text

### CODE REVIEW

**Comment by stockiNail** [comment]
@LeeLenaleee sorry for boring you, I have the feeling that to be 100% compatible with chart.js 4 some additional updates to package.json should be applied, but  I could be wrong. I don't have so much experience on JS packaging. See https://github.com/chartjs/chartjs-plugin-annotation/issues/814

**Comment by LeeLenaleee** [comment]
Will see if I have time tonight to look at it

**Comment by stockiNail** [comment]
> Will see if I have time tonight to look at it

FYI, I have tried to apply some updates, following adapter luxon) on annotation plugin. PR https://github.com/chartjs/chartjs-plugin-annotation/pull/815

**Comment by TobiasLessig** [comment]
Thanks for the contribution guys. Is there an estimated schedule on when to release the new version 2.2.0?

**Review by simonbrunel — APPROVED** [review]

**Pull request merged**
