### PR TITLE
Fix default when the plugin is defined in chart configuration

### LINKED ISSUE #285: The default `offset: 4` option is not working
This is the result with default `offset: 4`:
Captura de pantalla 2021-10-08 a las 9 56 40

With explicit `offset: 4`:
Captura de pantalla 2021-10-08 a las 9 57 06

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #285 

When the plugin is defined in chart configuration (and not globally registered) the offset and padding options were checked with a wrong default (0 instead of 4).

### CODE REVIEW

**Review by LeeLenaleee — APPROVED** [review]

**Comment by simonbrunel** [comment]
The suggested change is fine, though I would expect defaults to be applied even while using the plugin locally.

**Review by simonbrunel — APPROVED** [review]

**Comment by stockiNail** [comment]
> 

I was thinking the same. Maybe an issue should be submitted to chartjs project

**Comment by stockiNail** [comment]
@simonbrunel  I have seen that last merged PRs don't have the milestone. Will they be part of 2.1.0 or a bug fixing release 2.0.1?

**Comment by simonbrunel** [comment]
It will be 2.1.0 in which I would also like to include your other PR #271

**Pull request merged**
