### PR TITLE
Allow font names that contain spaces

### PR DESCRIPTION
**Pull request by teroman**

### CODE REVIEW

**Comment by simonbrunel** [comment]
@teroman can you share a test case that reproduces your issue?

Font family with spaces is supposed to work without extra quote:

https://jsfiddle.net/simonbrunel/svmec3ng/

Anyway, the suggested fix breaks a few use cases when multiple families: 
- `font.family: 'Open Sans, sans-serif'` becomes: `'"Open Sans, sans-serif"'` (doesn't work)
- `font.family: '"Open Sans", sans-serif` becomes: `'""Open Sans", sans-serif"'` (doesn't work)

https://jsfiddle.net/simonbrunel/5qtondr7 << need to be loaded twice, not sure why

**Comment by teroman** [comment]
Hi @simonbrunel , I have updated your example, one font has quotes the other doesn't:

https://jsfiddle.net/svmec3ng/9/

I tried a few font names, and "Bauhaus 93" seems to be the one that exhibits the issue. I think I got unlucky and assumed it was all fonts with a space as my change fixed the issue.

Now I'm not so sure what the issue is, but presumably it's related to the number in the font name.

**Comment by teroman** [comment]
Updated the other fiddle too here: https://jsfiddle.net/5qtondr7/18/
So it looks related to the canvas font setting.

**Comment by simonbrunel** [comment]
[According the MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#Syntax), `Bauhaus 93` without quote is not a valid name because of the numbers (but `Gill Sans Extrabold` without quote is valid). So I think that's the user responsibility to correctly quote names that need it (e.g. `{font: {family: '"Bauhaus 93"'}}`) and I would not try to support that case automatically in this plugin.

**Comment by teroman** [comment]
Totally agree, sorry for the spurious bug.

**Pull request closed without merging**
